### PR TITLE
Migrate CI to github Actions

### LINKED ISSUE #226: Migrate from Travis to GH Actions
## Expected Behaviour

Build test and deploy use Github Actions rather than travis

## Possible Solution

see changes made in arkade, for example.

### PR DESCRIPTION
**Pull request by Waterdrips**
Move from travis to Github Actions for build/test/release

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## Description
Fixes #226 
https://github.com/openfaas/faas/issues/1585

## Checklist:

I have:

- [x] checked my changes follow the style of the existing code / OpenFaaS repos
- [ ] updated the documentation and/or roadmap in README.md
- [ ] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
The Travis file needs to be removed and we have e2e tests that currently run. We need those also.

**Comment by Waterdrips** [comment]
> The Travis file needs to be removed and we have e2e tests that currently run. We need those also.

https://github.com/openfaas/ofc-bootstrap/pull/227/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R34 
^ adds `make all` to run all previosly run jobs

travis file is removed

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
@Waterdrips please can you run through the steps in this comment? https://github.com/openfaas/faas/issues/1585#issuecomment-725343317

In particular the setup go action needs to be used.

**Pull request merged**
